jekyll-remote-theme: vaibhavvikas/jekyll-theme-minimalistic
title: Professor Julius Ross 
description: University of Illinois Chicago
plugins:
  - jekyll-remote-theme

navigation:
  - name: About
    link: ./index.html
    sublist:
      - name: Image
        link: ./index.html#small-image
  - name: Teachihng
    link: ./teaching.html
