remote_theme: vaibhavvikas/jekyll-theme-minimalistic
title: Julius Ross
description: Mathematician
logo: ./media/juliusross.png
kramdown:
  input: kramdown
  math_engine: mathjax
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
navigation:
  - name: About
    link: ./

  - name: Research
    link: ./research
    sublist:
      - name: Papers
        link: ./papers
      - name: Software
        link: ./software

  - name: Teaching
    link: ./teaching

  - name: Advising
    link: ./advising
    sublist:
      - name: Undergraduate
        link: ./undergraduate
      - name: Graduate
        link: ./graduate
      - name: Readings
        link: ./readings
  - name: Activities
    link: ./activities
  - name: Other
    link: ./other
    sublist:
      - name: Pets
        link: ./pets
      - name: Movies
        link: ./movies

