remote_theme: vaibhavvikas/jekyll-theme-minimalistic

title: Julius Ross
description: Mathematician

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  
navigation:
  - name: About
    link: ./

  - name: Research
    link: ./research.html
    sublist:
      - name: Papers
        link: ./papers.md
      - name: Software
        link: ./software.md

  - name: Teaching
    link: ./teaching.html

  - name: Advising
    link: ./advising.html
    sublist:
      - name: Undergraduate
        link: ./undergraduate.md
      - name: Graduate
        link: ./graduate.md

  - name: Activities
    link: ./activities.html
    sublist:
      - name: Past Activities
        link: ./pastactivities.md

  - name: Other
    link: ./other.html
    sublist:
      - name: Pets
        link: ./pets.md
      - name: Movies
        link: ./movies.md

