remote_theme: vaibhavvikas/jekyll-theme-minimalistic

title: Julius Ross
description: Mathematician

navigation:
  - name: Home Page
    link: ./
    sublist:
      - name: Usage
        link: ./#usage
      - name: Customizing
        link: ./#customizing
      - name: Customizing Sidebar
        link: ./#customizing-sidebar
      - name: Navigation
        link: ./#navigation
      - name: Example
        link: ./#example
      - name: Stylesheet
        link: ./#stylesheet
      - name: Credits
        link: ./#credits
  - name: Teaching
    link: ./teaching.html
