jekyll-remote-theme: vaibhavvikas/jekyll-theme-minimalistic
title: Professor Julius Ross 
description: University of Illinois Chicago

navigation:
  - name: About
    link: ./index.md
    sublist:
      - name: Image
        link: ./index.html#small-image
  - name: Teachihng
    link: ./teaching.md
